### ISSUE TITLE
requirements.txt needs macOS to build.

### ISSUE THREAD

**Issue by iplayfast** [danielgross/localpilot#1]
pip install -r requirements.txt 
Defaulting to user installation because normal site-packages is not writeable
Collecting anyio==4.0.0 (from -r requirements.txt (line 1))
  Obtaining dependency information for anyio==4.0.0 from https://files.pythonhosted.org/packages/36/55/ad4de788d84a630656ece71059665e01ca793c04294c463fd84132f40fe6/anyio-4.0.0-py3-none-any.whl.metadata
  Using cached anyio-4.0.0-py3-none-any.whl.metadata (4.5 kB)
Collecting certifi==2023.7.22 (from -r requirements.txt (line 2))
  Obtaining dependency information for certifi==2023.7.22 from https://files.pythonhosted.org/packages/4c/dd/2234eab22353ffc7d94e8d13177aaa050113286e93e7b40eae01fbf7c3d9/certifi-2023.7.22-py3-none-any.whl.metadata
  Using cached certifi-2023.7.22-py3-none-any.whl.metadata (2.2 kB)
Collecting charset-normalizer==3.3.0 (from -r requirements.txt (line 3))
  Obtaining dependency information for charset-normalizer==3.3.0 from https://files.pythonhosted.org/packages/5d/42/9d11cb5f3326501d7e913d2581a4e3b237ef7ee3e121b2faa89c1676125b/charset_normalizer-3.3.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Using cached charset_normalizer-3.3.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (32 kB)
Collecting click==8.1.7 (from -r requirements.txt (line 4))
  Obtaining dependency information for click==8.1.7 from https://files.pythonhosted.org/packages/00/2e/d53fa4befbf2cfa713304affc7ca780ce4fc1fd8710527771b58311a3229/click-8.1.7-py3-none-any.whl.metadata
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: exceptiongroup==1.1.3 in /home/chris/.local/lib/python3.10/site-packages (from -r requirements.txt (line 5)) (1.1.3)
Requirement already satisfied: h11==0.14.0 in /home/chris/.local/lib/python3.10/site-packages (from -r requirements.txt (line 6)) (0.14.0)
Collecting httpcore==0.18.0 (from -r requirements.txt (line 7))
  Obtaining dependency information for httpcore==0.18.0 from https://files.pythonhosted.org/packages/ac/97/724afbb7925339f6214bf1fdb5714d1a462690466832bf8fb3fd497649f1/httpcore-0.18.0-py3-none-any.whl.metadata
  Using cached httpcore-0.18.0-py3-none-any.whl.metadata (18 kB)
Collecting httpx==0.25.0 (from -r requirements.txt (line 8))
  Obtaining dependency information for httpx==0.25.0 from https://files.pythonhosted.org/packages/33/0d/d9ce469af019741c8999711d36b270ff992ceb1a0293f73f9f34fdf131e9/httpx-0.25.0-py3-none-any.whl.metadata
  Using cached httpx-0.25.0-py3-none-any.whl.metadata (7.6 kB)
Requirement already satisfied: idna==3.4 in /home/chris/.local/lib/python3.10/site-packages (from -r requirements.txt (line 9)) (3.4)
Collecting pyobjc-core==10.0 (from -r requirements.txt (line 10))
  Using cached pyobjc-core-10.0.tar.gz (921 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [2 lines of output]
      running egg_info
      error: PyObjC requires macOS to build
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
(localpilot) chris@FORGE:~/ai/localpilot$ pip install pyobjc-core
Defaulting to user installation because normal site-packages is not writeable
Collecting pyobjc-core
  Using cached pyobjc-core-10.0.tar.gz (921 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [2 lines of output]
      running egg_info
      error: PyObjC requires macOS to build
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by danielgross** [comment]
Yep. If you want to make it multiplatform, please submit a PR.
