### ISSUE TITLE
Docker localpilot

### ISSUE THREAD

**Issue by o6uoq** [danielgross/localpilot#3]
**As a** `localpilot` user
**I want** a Docker container
**So that** I can run `localpilot` with a simple `docker` command rather than installing and running Python et al. from my local env

**Comment by danielgross** [comment]
Please submit pull request!

**Comment by o6uoq** [comment]
I've tried to build a Docker container using a slimline Python image as well as the `sickcodes/docker-osx` container. This doesn't work for this reason:

```
9.994   × Getting requirements to build wheel did not run successfully.
9.994   │ exit code: 1
9.994   ╰─> [2 lines of output]
9.994       running egg_info
9.994       error: PyObjC requires macOS to build
9.994       [end of output]
```

I couldn't find any obvious way to circumvent the PyObjC depends on macOS. Would you happen to know of a way, or if `PyObjC` can be replaced? Anything which has a depends on macOS will not work in a Docker container.

If I find anything I'll update this GitHub issue.
